server {
    listen       80;
    server_name  dearme.cc;
    charset      utf-8;
    root         /var/www/dearme/frontend;

    location / {
        index  index.html;
    }

    location /test/ { index index.html; }
    location /js/   { }
    location /css/  { }
    location /assets/ { }

    error_page 404 /404.html;
}
